# Generated by Django 6.0.6 on 2026-06-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipment_status_alter_statusupdate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='distance',
        ),
        migrations.AddField(
            model_name='shipment',
            name='description',
            field=models.CharField(blank=True, help_text='Brief item description', max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of items'),
        ),
    ]
